language: node_js
node_js: '8'
os:
- linux
- osx
- windows
dist: xenial
cache:
- npm: true
- yarn: true
env:
- YARN_GPG=no
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
install: yarn
script: yarn ci
after_success:
- nyc report --reporter=text-lcov > coverage.lcov
- $(npm bin)/codecov
